# Generated by Django 3.2.3 on 2021-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
