# Generated by Django 3.2.3 on 2021-05-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtitle_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTitle',
            new_name='JobSearchFilters',
        ),
    ]
