# Generated by Django 3.2.3 on 2021-05-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_jobtitle_jobsearchfilters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearchfilters',
            name='start_date',
        ),
    ]
