# Generated by Django 3.2.3 on 2021-05-29 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobsearchfilters_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchfilters',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
