# Generated by Django 3.2.3 on 2021-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobsearchfilters_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearchfilters',
            name='job_title',
            field=models.CharField(choices=[('ml', 'ML'), ('cv', 'CV'), ('ds', 'DS'), ('nlp', 'NLP')], default='ml', max_length=6),
        ),
    ]
